apiVersion: v1
data:
  config.yaml: "\"auth_enabled\": true\n\"ingester\": \n  \"lifecycler\": \n    \"heartbeat_period\":
    \"5s\"\n    \"interface_names\": \n    - \"eth0\"\n    \"join_after\": \"10s\"\n
    \   \"num_tokens\": 512\n    \"ring\": \n      \"consul\": \n        \"consistentreads\":
    true\n        \"host\": \"consul.loki.svc.cluster.local:8500\"\n        \"httpclienttimeout\":
    \"20s\"\n        \"prefix\": \"\"\n      \"heartbeat_timeout\": \"1m\"\n      \"replication_factor\":
    3\n      \"store\": \"consul\"\n\"schema_config\": \n  \"configs\": \n  - \"from\":
    \"0\"\n    \"index\": \n      \"period\": \"168h\"\n      \"prefix\": \"loki_index_\"\n
    \   \"object_store\": \"gcs\"\n    \"schema\": \"v9\"\n    \"store\": \"bigtable\"\n\"server\":
    \n  \"graceful_shutdown_timeout\": \"5s\"\n  \"grpc_listen_port\": 9095\n  \"grpc_server_max_recv_msg_size\":
    67108864\n  \"http_listen_port\": 80\n  \"http_server_idle_timeout\": \"120s\"\n
    \ \"http_server_read_timeout\": \"30s\"\n  \"http_server_write_timeout\": \"30s\"\n
    \ \"log_level\": \"info\"\n\"storage_config\": \n  \"aws\": {}\n  \"bigtable\":
    {}\n  \"gcs\": {}"
kind: ConfigMap
metadata:
  name: loki
  namespace: loki
